num = int(input('Gafanhoto, digita um número aí! = '))
print('TABUADA DE {} '.format(num))
print('{:3} X 1  = {:3}'.format(num, num*1))
print('{:3} X 2  = {:3}'.format(num, num*2))
print('{:3} X 3  = {:3}'.format(num, num*3))
print('{:3} X 4  = {:3}'.format(num, num*4))
print('{:3} X 5  = {:3}'.format(num, num*5))
print('{:3} X 6  = {:3}'.format(num, num*6))
print('{:3} X 7  = {:3}'.format(num, num*7))
print('{:3} X 8  = {:3}'.format(num, num*8))
print('{:3} X 9  = {:3}'.format(num, num*9))
print('{:3} X 10 = {:3}'.format(num, num*10))
