val = input('Digite algo: ')
print('-----APURAÇÃO-----')
print('Tipo------------------->', type(val))
print('É número?-------------->', val.isnumeric())
print('É caractere?----------->', val.isalpha())
print('É número e caractere?-->', val.isalnum())
print('É todo maiúsculo?------>', val.isupper())
print('É todo minúsculo?------>', val.islower())
print('É decimal?------------->', val.isdecimal())
print('É somente espaço?------>', val.isspace())
print('Digit------------------>', val.isdigit())
print('Printable-------------->', val.isprintable())
print('Identifier------------->', val.isidentifier())
print('Está capitalizada?----->', val.istitle())
